import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./_components/theme";
import { SettingsProvider } from "./contexts/SettingsContext";
import { SettingsValueProps } from "./_components/settings/types";
import { CssBaseline } from "@mui/material";
import StoreProvider from "./StoreProvider";

// Define the default settings according to SettingsValueProps
const settings: SettingsValueProps = {
  themeMode: "light",
  themeLayout: "horizontal",
  autoThemeMode: true,
  themeStretch: false,
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Feedflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        {/* <SettingsProvider defaultSettings={settings}>
        <ThemeProvider> */}
        <CssBaseline />
        <body className={inter.className}>{children}</body>
        {/* </ThemeProvider>
      </SettingsProvider> */}
      </StoreProvider>
    </html>
  );
}
